name: customer-service
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - langchain
      - langchain-core
      - langchain-community
      - python-dotenv
